/* import the fontawesome core */
import { library } from "@fortawesome/fontawesome-svg-core";

/* import font awesome icon component */
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

/* import specific icons */
import {
  faDownload,
  faPrint,
  faFileWord,
  faAngleLeft,
  faUserSecret,
  faFileExcel,
  faCircleXmark,
  faStar,
  faSearch,
  faArrowLeft,
  faDoorOpen,
  faClose,
  faReply,
  faCheck,
  faHand,
  faEnvelope,
  faMagnifyingGlass,
  faFolderOpen,
  faThumbsDown,
  faHourglassStart,
  faPaperPlane,
  faEye,
  faInfo,
  faCircleInfo,
  faBars,
  faTimes,
  faAngleRight,
  faTruckMoving,
  faArrowRight,
  faBold,
  faItalic,
  faStrikethrough,
  faCode,
  faCirclePlus,
  faParagraph,
  faFileImage,
  faLocationDot,
  faQuoteLeft,
  faList,
  faImage,
  faUndo,
  faRedo,
  faTrash,
  faPenToSquare,
  faPhone,
  faPlus,
  faMinus,
  faAngleDown,
} from "@fortawesome/free-solid-svg-icons";
/* add icons to the library */
library.add(
  faFileWord,
  faStar,
  faDownload,
  faLocationDot,
  faCirclePlus,
  faPrint,
  faFileImage,
  faAngleLeft,
  faUserSecret,
  faMagnifyingGlass,
  faFileExcel,
  faAngleRight,
  faCircleXmark,
  faSearch,
  faTruckMoving,
  faAngleDown,
  faArrowLeft,
  faDoorOpen,
  faClose,
  faReply,
  faCheck,
  faHand,
  faEnvelope,
  faPaperPlane,
  faFolderOpen,
  faHourglassStart,
  faThumbsDown,
  faInfo,
  faCircleInfo,
  faBars,
  faTimes,
  faArrowRight,
  faBold,
  faItalic,
  faStrikethrough,
  faCode,
  faParagraph,
  faQuoteLeft,
  faList,
  faImage,
  faUndo,
  faRedo,
  faCircleInfo,
  faTrash,
  faPenToSquare,
  faPhone,
  faPlus,
  faMinus
);

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component("font-awesome-icon", FontAwesomeIcon);
});
