// <auto-generated />
using System;
using GlobalAI.DataAccess.Base;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace GlobalAI.HostConsole.Migrations
{
    [DbContext(typeof(GlobalAIDbContext))]
    [Migration("20230517144356_add-tbl-province")]
    partial class addtblprovince
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GlobalAI.CoreEntities.DataEntities.CoreProvince", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("CODE");

                    b.Property<int>("AdministrativeRegionId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ADMINISTRATIVE_REGION_ID");

                    b.Property<int>("AdministrativeUnitId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ADMINISTRATIVE_UNIT_ID");

                    b.Property<string>("CodeName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODE_NAME");

                    b.Property<string>("FullName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FULL_NAME");

                    b.Property<string>("FullNameEn")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FULL_NAME_EN");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NAME");

                    b.Property<string>("NameEn")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NAME_EN");

                    b.HasKey("Code");

                    b.ToTable("C_PROVINCES");
                });

            modelBuilder.Entity("GlobalAI.CoreEntities.DataEntities.CoreRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(25)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CODE");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("CREATED_DATE");

                    b.Property<bool>("Deleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("DELETED");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("DELETED_BY");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("DELETED_DATE");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("MODIFIED_BY");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("MODIFIED_DATE");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("C_ROLE", t =>
                        {
                            t.HasComment("Bảng role");
                        });
                });

            modelBuilder.Entity("GlobalAI.CoreEntities.DataEntities.CoreRolePermisison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("CREATED_DATE");

                    b.Property<bool>("Deleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("DELETED");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("DELETED_BY");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("DELETED_DATE");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("MODIFIED_BY");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("MODIFIED_DATE");

                    b.Property<string>("PermissionKey")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PERMISSION_KEY");

                    b.Property<int>("RoleId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ROLE_ID");

                    b.HasKey("Id");

                    b.ToTable("C_ROLE_PERMISSION");
                });

            modelBuilder.Entity("GlobalAI.CoreEntities.DataEntities.CoreUserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("CREATED_DATE");

                    b.Property<bool>("Deleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("DELETED");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("DELETED_BY");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("DELETED_DATE");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("MODIFIED_BY");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("MODIFIED_DATE");

                    b.Property<int>("RoleId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ROLE_ID");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.ToTable("C_USER_ROLE");
                });

            modelBuilder.Entity("GlobalAI.CoreEntities.DataEntities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USER_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("AVATAR");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("CREATED_DATE");

                    b.Property<bool>("Deleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("DELETED");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("DELETED_BY");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("DELETED_DATE");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("DISPLAY_NAME");

                    b.Property<string>("Email")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EMAIL");

                    b.Property<decimal?>("FailAttemp")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("FAIL_ATTEMP");

                    b.Property<string>("FirstName")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("FIRST_NAME");

                    b.Property<decimal?>("GPoint")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("G_POINT");

                    b.Property<bool>("IsFirstTime")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_FIRST_TIME");

                    b.Property<bool>("IsTempPassword")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_TEMP_PASSWORD");

                    b.Property<bool>("IsVerifiedEmail")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_VERIFIED_EMAIL");

                    b.Property<DateTime?>("LastFailedLogin")
                        .HasColumnType("DATE")
                        .HasColumnName("LAST_FAILED_LOGIN");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("DATE")
                        .HasColumnName("LAST_LOGIN");

                    b.Property<string>("LastName")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("LAST_NAME");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("MODIFIED_BY");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("MODIFIED_DATE");

                    b.Property<string>("Password")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PHONE");

                    b.Property<string>("Policy")
                        .HasColumnType("CLOB")
                        .HasColumnName("POLICY");

                    b.Property<string>("ResetPasswordToken")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("RESET_PASSWORD_TOKEN");

                    b.Property<DateTime?>("ResetPasswordTokenExp")
                        .HasColumnType("DATE")
                        .HasColumnName("RESET_PASSWORD_TOKEN_EXP");

                    b.Property<string>("Status")
                        .HasMaxLength(3)
                        .HasColumnType("CHAR")
                        .HasColumnName("STATUS");

                    b.Property<string>("UserType")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("USER_TYPE");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("USERNAME");

                    b.Property<string>("VerifyEmailCode")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("VERIFY_EMAIL_CODE");

                    b.HasKey("UserId");

                    b.ToTable("USER", t =>
                        {
                            t.HasComment("User");
                        });
                });

            modelBuilder.Entity("GlobalAI.ProductEntities.DataEntities.BaiTin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("CREATED_DATE");

                    b.Property<bool>("Deleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("DELETED");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("DELETED_BY");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("DELETED_DATE");

                    b.Property<int>("IdDanhMuc")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DANH_MUC");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("MO_TA");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("MODIFIED_BY");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("MODIFIED_DATE");

                    b.Property<DateTime?>("NgayDang")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("NGAY_DANG");

                    b.Property<string>("NoiDung")
                        .HasColumnType("CLOB")
                        .HasColumnName("NOI_DUNG");

                    b.Property<string>("Slug")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("SLUG");

                    b.Property<int?>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("THUMBNAIL");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("TIEU_DE");

                    b.HasKey("Id");

                    b.ToTable("P_BaiTin", t =>
                        {
                            t.HasComment("Bảng bài tin");
                        });
                });

            modelBuilder.Entity("GlobalAI.ProductEntities.DataEntities.ChiTietDonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("CREATED_DATE");

                    b.Property<bool>("Deleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("DELETED");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("DELETED_BY");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("DELETED_DATE");

                    b.Property<decimal?>("GPoint")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("G_POINT");

                    b.Property<int>("IdDonHang")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DON_HANG");

                    b.Property<int>("IdSanPham")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SAN_PHAM");

                    b.Property<int>("IdSanPhamChiTiet")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SAN_PHAM_CHI_TIET");

                    b.Property<int>("SoLuong")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SO_LUONG");

                    b.HasKey("Id");

                    b.ToTable("P_ChiTietDonHang", t =>
                        {
                            t.HasComment("bảng chi tiết đơn hàng");
                        });
                });

            modelBuilder.Entity("GlobalAI.ProductEntities.DataEntities.ChiTietTraGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("CREATED_DATE");

                    b.Property<bool>("Deleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("DELETED");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("DELETED_BY");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("DELETED_DATE");

                    b.Property<decimal?>("GiaTien")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("GIA_TIEN");

                    b.Property<int>("IdTraGia")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TRA_GIA");

                    b.Property<int>("LoaiTraGia")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("LOAI_TRA_GIA");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("MODIFIED_BY");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("MODIFIED_DATE");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Usertype")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("USERTYPE");

                    b.HasKey("Id");

                    b.ToTable("P_ChiTietTraGia", t =>
                        {
                            t.HasComment("Chi tiết trả giá");
                        });
                });

            modelBuilder.Entity("GlobalAI.ProductEntities.DataEntities.DanhMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("CREATED_DATE");

                    b.Property<bool>("Deleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("DELETED");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("DELETED_BY");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("DELETED_DATE");

                    b.Property<string>("IdDanhMuc")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ID_DANH_MUC");

                    b.Property<bool>("IsDisplayOnHomePage")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_DISPLAY_ON_HOME_PAGE");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("MODIFIED_BY");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("MODIFIED_DATE");

                    b.Property<string>("TenDanhMuc")
                        .HasMaxLength(400)
                        .HasColumnType("NVARCHAR2(400)")
                        .HasColumnName("TEN_DANH_MUC");

                    b.HasKey("Id");

                    b.ToTable("P_DanhMuc", t =>
                        {
                            t.HasComment("Demo bảng danh mục sản phẩm");
                        });
                });

            modelBuilder.Entity("GlobalAI.ProductEntities.DataEntities.DanhMucBaiTin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("CREATED_DATE");

                    b.Property<bool>("Deleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("DELETED");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("DELETED_BY");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("DELETED_DATE");

                    b.Property<string>("MaDanhMuc")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("MA_DANH_MUC");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("MODIFIED_BY");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("MODIFIED_DATE");

                    b.Property<int?>("ParentId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PARENT_ID");

                    b.Property<int?>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.Property<string>("TenDanhMuc")
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("TEN_DANH_MUC");

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("THUMBNAIL");

                    b.HasKey("Id");

                    b.ToTable("P_DanhMucBaiTin", t =>
                        {
                            t.HasComment("Bảng danh mục bài tin");
                        });
                });

            modelBuilder.Entity("GlobalAI.ProductEntities.DataEntities.DanhMucThuocTinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("CREATED_DATE");

                    b.Property<bool>("Deleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("DELETED");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("DELETED_BY");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("DELETED_DATE");

                    b.Property<string>("Ma")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("MA");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("MODIFIED_BY");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("MODIFIED_DATE");

                    b.Property<string>("Ten")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("TEN");

                    b.HasKey("Id");

                    b.ToTable("P_DanhMucThuocTinh", t =>
                        {
                            t.HasComment("Demo bảng danh mục thuộc tính");
                        });
                });

            modelBuilder.Entity("GlobalAI.ProductEntities.DataEntities.DonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("CREATED_DATE");

                    b.Property<bool>("Deleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("DELETED");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("DELETED_BY");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("DELETED_DATE");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(1000)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("DIA_CHI");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(4000)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("GHI_CHU");

                    b.Property<string>("HinhThucThanhToan")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("HINH_THUC_THANH_TOAN");

                    b.Property<int?>("IdGStore")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_G_STORE");

                    b.Property<int?>("IdNguoiMua")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_NGUOI_MUA");

                    b.Property<string>("MaDonHang")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MA_DON_HANG");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("MODIFIED_BY");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("MODIFIED_DATE");

                    b.Property<DateTime?>("NgayHoanThanh")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("NGAY_HOAN_THANH");

                    b.Property<decimal?>("SoTien")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("SO_TIEN");

                    b.Property<int?>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(1000)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("THUMBNAIL");

                    b.HasKey("Id");

                    b.ToTable("P_DonHang", t =>
                        {
                            t.HasComment("Đơn hàng");
                        });
                });

            modelBuilder.Entity("GlobalAI.ProductEntities.DataEntities.GioHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("CREATED_DATE");

                    b.Property<bool>("Deleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("DELETED");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("DELETED_BY");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("DELETED_DATE");

                    b.Property<int>("IdNguoiMua")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_NGUOI_MUA");

                    b.Property<int?>("IdSanPham")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SAN_PHAM");

                    b.Property<int?>("IdSanPhamChiTiet")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SAN_PHAM_CHI_TIET");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("MODIFIED_BY");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("MODIFIED_DATE");

                    b.Property<int>("SoLuong")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SO_LUONG");

                    b.Property<int?>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.ToTable("P_GioHang", t =>
                        {
                            t.HasComment("Giỏ hàng");
                        });
                });

            modelBuilder.Entity("GlobalAI.ProductEntities.DataEntities.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("CREATED_DATE");

                    b.Property<bool>("Deleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("DELETED");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("DELETED_BY");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("DELETED_DATE");

                    b.Property<decimal?>("GiaBan")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("GIA_BAN");

                    b.Property<decimal?>("GiaChietKhau")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("GIA_CHIET_KHAU");

                    b.Property<decimal?>("GiaToiThieu")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("GIA_TOI_THIEU");

                    b.Property<string>("IdDanhMuc")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ID_DANH_MUC");

                    b.Property<int?>("IdDanhMucThuocTinh")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DANH_MUC_THUOC_TINH");

                    b.Property<int>("IdGStore")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_G_STORE");

                    b.Property<int?>("LuotBan")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("LUOT_BAN");

                    b.Property<int?>("LuotXem")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("LUOT_XEM");

                    b.Property<string>("MaSanPham")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MA_SAN_PHAM");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("MO_TA");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("MODIFIED_BY");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("MODIFIED_DATE");

                    b.Property<DateTime>("NgayDangKi")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("NGAY_DANG_KI");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("NGAY_DUYET");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.Property<string>("TenSanPham")
                        .HasMaxLength(400)
                        .HasColumnType("NVARCHAR2(400)")
                        .HasColumnName("TEN_SAN_PHAM");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("THUMBNAIL");

                    b.HasKey("Id");

                    b.ToTable("P_SanPham", t =>
                        {
                            t.HasComment("bảng sản phẩm");
                        });
                });

            modelBuilder.Entity("GlobalAI.ProductEntities.DataEntities.SanPhamChiTiet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("CREATED_DATE");

                    b.Property<bool>("Deleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("DELETED");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("DELETED_BY");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("DELETED_DATE");

                    b.Property<decimal?>("GiaBan")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("GIA_BAN");

                    b.Property<decimal?>("GiaChietKhau")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("GIA_CHIET_KHAU");

                    b.Property<decimal?>("GiaToiThieu")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("GIA_TOI_THIEU");

                    b.Property<int>("IdSanPham")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SAN_PHAM");

                    b.Property<int?>("LuotBan")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("LUOT_BAN");

                    b.Property<int?>("LuotXem")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("LUOT_XEM");

                    b.Property<string>("MaSanPhamChiTiet")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MA_SAN_PHAM_CHI_TIET");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("MO_TA");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("MODIFIED_BY");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("MODIFIED_DATE");

                    b.Property<DateTime>("NgayDangKi")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("NGAY_DANG_KI");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("NGAY_DUYET");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SO_LUONG");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("THUMBNAIL");

                    b.HasKey("Id");

                    b.ToTable("P_SanPhamChiTiet", t =>
                        {
                            t.HasComment("bảng sản phẩm chi tiết");
                        });
                });

            modelBuilder.Entity("GlobalAI.ProductEntities.DataEntities.SanPhamChiTietThuocTinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("CREATED_DATE");

                    b.Property<bool>("Deleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("DELETED");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("DELETED_BY");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("DELETED_DATE");

                    b.Property<int>("IdSanPhamChiTiet")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SAN_PHAM_CHI_TIET");

                    b.Property<int>("IdThuocTinhGiaTri")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_THUOC_TINH_GIA_TRI");

                    b.HasKey("Id");

                    b.ToTable("P_SanPhamChiTietThuocTinh", t =>
                        {
                            t.HasComment("bảng nối giữa Sản phẩm chi tiết & Thuộc tính giá trị");
                        });
                });

            modelBuilder.Entity("GlobalAI.ProductEntities.DataEntities.ThuocTinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("CREATED_DATE");

                    b.Property<bool>("Deleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("DELETED");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("DELETED_BY");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("DELETED_DATE");

                    b.Property<int>("IdDanhMucThuocTinh")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DANH_MUC_THUOC_TINH");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("MODIFIED_BY");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("MODIFIED_DATE");

                    b.Property<string>("TenThuocTinh")
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("TEN_THUOC_TINH");

                    b.HasKey("Id");

                    b.ToTable("P_ThuocTinh", t =>
                        {
                            t.HasComment("bảng thuộc tính theo danh mục");
                        });
                });

            modelBuilder.Entity("GlobalAI.ProductEntities.DataEntities.ThuocTinhGiaTri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("CREATED_DATE");

                    b.Property<bool>("Deleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("DELETED");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("DELETED_BY");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("DELETED_DATE");

                    b.Property<string>("GiaTri")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("GIA_TRI");

                    b.Property<int>("IdThuocTinh")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_THUOC_TINH");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("MODIFIED_BY");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("MODIFIED_DATE");

                    b.Property<string>("TenThuocTinh")
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("TEN_THUOC_TINH");

                    b.HasKey("Id");

                    b.ToTable("P_ThuocTinhGiaTri", t =>
                        {
                            t.HasComment("bảng giá trị thuộc tính");
                        });
                });

            modelBuilder.Entity("GlobalAI.ProductEntities.DataEntities.TraGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("CREATED_DATE");

                    b.Property<bool>("Deleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("DELETED");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("DELETED_BY");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("DELETED_DATE");

                    b.Property<decimal>("GiaCuoi")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("GIA_CUOI");

                    b.Property<int>("IdNguoiBan")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_NGUOI_BAN");

                    b.Property<int>("IdNguoiMua")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_NGUOI_MUA");

                    b.Property<int>("IdSanPham")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SAN_PHAM");

                    b.Property<int>("IdSanPhamChiTiet")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SAN_PHAM_CHI_TIET");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("MODIFIED_BY");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("MODIFIED_DATE");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("NOI_DUNG");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.ToTable("P_TraGia", t =>
                        {
                            t.HasComment("Trả giá");
                        });
                });

            modelBuilder.Entity("GlobalAI.ProductEntities.DataEntities.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("AVATAR");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("CREATED_DATE");

                    b.Property<bool>("Deleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("DELETED");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("DELETED_BY");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("DELETED_DATE");

                    b.Property<double?>("GiaTri")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("GIA_TRI");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("MO_TA");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("MODIFIED_BY");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("MODIFIED_DATE");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("NAME");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("DATE")
                        .HasColumnName("NGAY_HET_HAN");

                    b.Property<int>("SoLuong")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SO_LUONG");

                    b.Property<int?>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.ToTable("P_Voucher", t =>
                        {
                            t.HasComment("Voucher");
                        });
                });

            modelBuilder.Entity("GlobalAI.ProductEntities.DataEntities.VoucherChiTiet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("CREATED_DATE");

                    b.Property<bool>("Deleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("DELETED");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("DELETED_BY");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("DELETED_DATE");

                    b.Property<double?>("LichSuGiaTri")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("LICH_SU_GIA_TRI");

                    b.Property<string>("LichSuMoTa")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("LICH_SU_MO_TA");

                    b.Property<string>("LichSuTenVoucher")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("LICH_SU_TEN_VOUCHER");

                    b.Property<string>("MaVoucher")
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("MA_VOUCHER");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("MODIFIED_BY");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("MODIFIED_DATE");

                    b.Property<DateTime?>("NgayGiao")
                        .HasColumnType("DATE")
                        .HasColumnName("NGAY_GIAO");

                    b.Property<DateTime?>("NgaySuDung")
                        .HasColumnType("DATE")
                        .HasColumnName("NGAY_SU_DUNG");

                    b.Property<string>("NguoiSuDung")
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("NGUOI_SU_DUNG");

                    b.Property<int?>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.Property<int>("VoucherId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VOUCHER_ID");

                    b.HasKey("Id");

                    b.ToTable("P_Voucher_ChiTiet", t =>
                        {
                            t.HasComment("Voucher chi tiết");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
